### ISSUE TITLE
Reevaluate all jsdoc for @private

### ISSUE THREAD

**Issue by ckohen** [ckohen/platiBot#13]
Many of the currently private properties / methods should be public.
A few of the currently public properties / methods should be private
- [x] Remove all @private
- [x] Examine the docs to see what should be @private
- [x] Put @private where determined
